x = (input('Digite algo:  '))
print('Número digitado {}'.format(x))
print('Tipo: ', type(x))
print('Ele é um número? ', x.isnumeric())
print('Ele é alfabetico? ', x.isalpha())
print('Ele é alphanumérico? ', x.isalnum())
print('Está com letra maiscula? ', x.isupper())
print('Está com letra minuscula? ', x.islower())
print('Possui algum espaço? ', x.isspace())
print('Está capitalizada? ', x.istitle())
