print('=='*20)
nome = str(input('Digite seu nome: ')).strip()
print('=='*20)
print('         ANÁLISE:      ')
print('=='*20)
print('Formatação Maiúscula: {} '.format(nome.upper()))
print('Formatação Minúscula: {} '.format(nome.lower()))
print('Seu nome tem: {} letras'.format(len(nome) - nome.count(' ')))
nome = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(nome[0],len(nome[0])))
print('=='*20)