print('=='*20)
sal = float(input('Digite o seu salário: '))
aumento = sal + (sal * (15/100))
print('Parabéns! Você ganhou um aumento! Agora seu novo salário é de {} reais.'.format(aumento))
print('=='*20)